---
server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/task-tracker
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    #show-sql: true

